Repository ember-tooling/snippets, pull requests merged in 2025-04, with the labels that each got.

#1 Get started
  .github/workflows/ci.yml
  .gitignore
  .prettierignore
  CHANGELOG.md
  README.md
  images/ember-e-circle-icon-4c.png
  images/ember-e-circle-icon-4c.svg
  package.json
  pnpm-lock.yaml
  snippets/all-template-tag.json
  snippets/all.json
  snippets/javascript.glimmer.json
  snippets/javascript.json
  snippets/typescript.glimmer.json
  snippets/typescript.json
Labels: enhancement

#4 Add installation instructions
  README.md
Labels: documentation

#3 Update badge urls
  README.md
Labels: documentation

#6 Script to generate the list of snippets
  generate.mjs
  package.json
Labels: bug
